# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XJMapSDK_Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  #pod 'XJMapSDK'
  #本地路径
  pod 'XJMapSDK', :path => '../'
  #git路径
  #pod 'XJMapSDK', :git => 'https://github.com/xunji-iot/XJMapSDK-iOS.git'
  #pod 'WechatOpenSDK'

end
